add precommit
rcaneill/xnemogcm pull request #84
Opened 2024-02-14 09:28 UTC by callumrollo

This draft PR adds some basic pre-commit hooks. This pre-commit will, among other things, satisfy the pyopensci requirement for automated linting

The linting is picking up quite a few PEP8 and spelling errors atm. These will need to be fixed. This also should be added to CI.

@rcaneill are you working on something similar already, or should I complete this PR?

2024-02-14 13:26 UTC, rcaneill commented
HI @callumrollo ,
I am not working on the linting for xnemogcm, so I'm happy to get your contributions!

2024-02-15 14:57 UTC, callumrollo commented
ok I think this is ready @rcaneill . Bit of a monster! Mostly spelling corrections and clearing out unused imports

2024-02-15 15:25 UTC, rcaneill commented on xnemogcm/namelist.py
It seems incorrect here to replace `nam` by `name` as `name` is already used in the for loop (line 27).

2024-02-15 15:27 UTC, rcaneill requested changes
Thanks for the great work! See my comment in file namelist.py

2024-02-16 10:49 UTC, rcaneill approved these changes

2024-02-16 10:49 UTC, merged